// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZKKi2lZuKufZbjXeEo8dJaeQIB13nKM8',
    appId: '1:605241253306:web:5a223818600e7d0c805183',
    messagingSenderId: '605241253306',
    projectId: 'viajapp-deployment',
    authDomain: 'viajapp-deployment.firebaseapp.com',
    storageBucket: 'viajapp-deployment.firebasestorage.app',
    measurementId: 'G-NFYSYZCQPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhU2YzV_t75ba2ctwzt13OuPI9q1fAy94',
    appId: '1:605241253306:android:30075a9370bb9e1e805183',
    messagingSenderId: '605241253306',
    projectId: 'viajapp-deployment',
    storageBucket: 'viajapp-deployment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrGQHkqGaMUxYzUmXsQ725KiWBLwxjbIw',
    appId: '1:605241253306:ios:4bfde4ea570adda9805183',
    messagingSenderId: '605241253306',
    projectId: 'viajapp-deployment',
    storageBucket: 'viajapp-deployment.firebasestorage.app',
    iosBundleId: 'com.example.viajapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrGQHkqGaMUxYzUmXsQ725KiWBLwxjbIw',
    appId: '1:605241253306:ios:4bfde4ea570adda9805183',
    messagingSenderId: '605241253306',
    projectId: 'viajapp-deployment',
    storageBucket: 'viajapp-deployment.firebasestorage.app',
    iosBundleId: 'com.example.viajapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZKKi2lZuKufZbjXeEo8dJaeQIB13nKM8',
    appId: '1:605241253306:web:42a68cfc0de57013805183',
    messagingSenderId: '605241253306',
    projectId: 'viajapp-deployment',
    authDomain: 'viajapp-deployment.firebaseapp.com',
    storageBucket: 'viajapp-deployment.firebasestorage.app',
    measurementId: 'G-4LE61022X6',
  );

}